### ISSUE TITLE
Footer should be stick at bottom

### ISSUE THREAD

**Issue by azhsetiawan** [eduayme/Rescue-app#40] opened 2019-10-15 09:08 UTC
Hi @eduayme

Maybe layout can be imporoved, especially footer.
That's better if footer stick/fixed at bottom screen

![rescue-Screen Shot 2019-10-15 at 15 48 10](https://user-images.githubusercontent.com/3045602/66817480-f7d24a00-ef65-11e9-9223-ff31059d7b60.png)

**Comment by eduayme** [comment] 2019-10-15 14:42
Hi @azhsetiawan 

Yes, good idea! Thanks

**Comment by eduayme** [comment] 2019-10-15 18:51
@azhsetiawan I have tried to do it. The problem is when scrolling, in pages with a height bigger than the screen, the footer scrolls too (it should be fixed at the bottom of the entire page) so this is why is not sticked.

**Comment by azhsetiawan** [comment] 2019-10-16 04:32
@eduayme let me try to make it

**Closed** 2019-10-16 12:34 UTC
Labels: enhancement
